stages:
  - test

image: cypress/browsers:chrome63-ff57

test:
  stage: test
  variables:
    DEBUG: cypress:*
  script:
    - npm cache clean -f
    - npm install --unsafe-perm
    - npm run build
    - npm run serve &
    - npm run cy:run
  artifacts:
    expire_in: 1 week
    paths:
      - cypress/screenshots/
      - cypress/videos/
